name: Run .NET Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: '0 */12 * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Instalar o Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar projeto sem restaurar dependências
        run: dotnet build --no-restore

      - name: Executar os testes
        run: dotnet test --no-build --verbosity normal
        
      - name: Upload de screenshots (se falhar)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: tests/screenshots/

